version: '3.5'

services:
  bbytesolutions:
    image: bonglv/bbytesolutions.com:1.0
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.bbytesolutions.loadbalancer.server.port=9999'
      - 'traefik.http.routers.traefik-public-http.rule=Host:home.bbyegroup.com'
    networks:
      - traefik-public
    ports:
      - 9999:80
    deploy: 
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M
      mode: replicated
      replicas: 2
networks:
  traefik-public:
    external: true