version: '3.8'

services:
  web1:
    image: bbytegroupcom/website-templates:v1
    hostname: web_1
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.web1-http.rule=Host(`demo1.bbytegroup.com`)
        - traefik.http.routers.web1-http.entrypoints=http
        - traefik.http.routers.web1-http.middlewares=https-redirect
        - traefik.http.routers.web1-https.rule=Host(`demo1.bbytegroup.com`)
        - traefik.http.routers.web1-https.entrypoints=https
        - traefik.http.routers.web1-https.tls=true
        - traefik.http.routers.web1-https.tls.certresolver=le
        - traefik.http.services.web1.loadbalancer.server.port=80
networks:
  traefik-public:
    external: true

# git pull && docker stack deploy -c docker-compose.yml web1