version: '3.8'

services:
  app-home:
    image: wordpress:4.9.8-apache
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.app-home-http.rule=Host(`home.bbytegroup.com`)
        - traefik.http.routers.app-home-http.entrypoints=http
        - traefik.http.routers.app-home-http.middlewares=https-redirect
        - traefik.http.routers.app-home-https.rule=Host(`home.bbytegroup.com`)
        - traefik.http.routers.app-home-https.entrypoints=https
        - traefik.http.routers.app-home-https.tls=true
        - traefik.http.routers.app-home-https.tls.certresolver=le
        - traefik.http.services.app-home.loadbalancer.server.port=8080
      depends_on:
          - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
    networks:
      - traefik-public
    labels:
      - traefik.enable=false
networks:
  traefik-public:
    external: true