version: '3.5'

services:
  bbytesolutions:
    image: bonglv/bbytesolutions.com:1.0
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik/traefik.toml:/traefik.toml'
      - './traefik/traefik_dynamic.toml:/traefik_dynamic.toml'
      - './traefik/acme.json:/acme.json'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.bbytesolutions.com.loadbalancer.server.port=9999'
    networks:
      - traefik-public
    ports:
      - 9999:80
    deploy: 
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M
      mode: replicated
      replicas: 2
networks:
  traefik-public:
    external: true