version: '3.3'

services:
  app:
    image: bonglv/bbytesolutions.com:1.0
    volumes:
      - bbytes-data:/var/opt/bbytes
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.bbytes.bbytes-data == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.bbytes-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.bbytes-http.entrypoints=http
        - traefik.http.routers.bbytes-http.middlewares=https-redirect
        - traefik.http.routers.bbytes-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.bbytes-https.entrypoints=https
        - traefik.http.routers.bbytes-https.tls=true
        - traefik.http.routers.bbytes-https.tls.certresolver=le
        - traefik.http.services.bbytes.loadbalancer.server.port=9000

networks:
  traefik-public:
    external: true

volumes:
  bbytes-data: