version: '3.8'

services:
  home2:
    image: bonglv/home:latest
    environment:
      - HOSTNAME=demo2.bbytesolutions.com
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.home2-http.rule=Host(`demo2.bbytegroup.com`)
        - traefik.http.routers.home2-http.entrypoints=http
        - traefik.http.routers.home2-http.middlewares=https-redirect
        - traefik.http.routers.home2-https.rule=Host(`demo2.bbytegroup.com`)
        - traefik.http.routers.home2-https.entrypoints=https
        - traefik.http.routers.home2-https.tls=true
        - traefik.http.routers.home2-https.tls.certresolver=le
        - traefik.http.services.home2.loadbalancer.server.port=80
networks:
  traefik-public:
    external: true