version: '3.5'

services:
  bbytesolutions:
    image: bonglv/bbytesolutions.com:1.0
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.bbytesolutions.com-http.rule=Host('home.bbytegroup.com')
        - traefik.http.routers.bbytesolutions.com-http.entrypoints=http
        - traefik.http.routers.bbytesolutions.com-http.middlewares=https-redirect
        - traefik.http.routers.bbytesolutions.com-https.rule=Host('home.bbytegroup.com')
        - traefik.http.routers.bbytesolutions.com-https.entrypoints=https
        - traefik.http.routers.bbytesolutions.com-https.tls=true
        - traefik.http.routers.bbytesolutions.com-https.tls.certresolver=le
        - traefik.http.services.bbytesolutions.com.loadbalancer.server.port=9999
    networks:
      - traefik-public
    ports:
      - 9999:80
    deploy: 
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M
      mode: replicated
      replicas: 2
networks:
  traefik-public:
    external: true