version: '3.8'

services:
  home:
    image: bonglv/home:latest
    environment:
      - HOSTNAME=demo1.bbytesolutions.com
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.home-data == true
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.home-http.rule=Host(`demo1.bbytegroup.com`)
        - traefik.http.routers.home-http.entrypoints=http
        - traefik.http.routers.home-http.middlewares=https-redirect
        - traefik.http.routers.home-https.rule=Host(`demo1.bbytegroup.com`)
        - traefik.http.routers.home-https.entrypoints=https
        - traefik.http.routers.home-https.tls=true
        - traefik.http.routers.home-https.tls.certresolver=le
        - traefik.http.services.home.loadbalancer.server.port=80
networks:
  traefik-public:
    external: true