version: '3.3'

services:
  app:
    image: bonglv/bbytesolutions.com:1.0
    networks:
      - traefik-public
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`home.bbytesgroup.com`)"
      - "traefik.http.routers.app.entrypoints=web"
networks:
  traefik-public:
    external: true