version: '3.8'

services:
  home:
    image: bonglv/home:latest
    ports:
      - "8080:80"
    environment:
      - HOSTNAME=home.bbytegroup.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.home-data == true
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.home-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.home-http.entrypoints=http
        - traefik.http.routers.home-http.middlewares=https-redirect
        - traefik.http.routers.home-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.home-https.entrypoints=https
        - traefik.http.routers.home-https.tls=true
        - traefik.http.routers.home-https.tls.certresolver=le
        - traefik.http.services.home.loadbalancer.server.port=8080
networks:
  traefik-public:
    external: true