version: '3.5'

services:
  bbytesolutions:
    image: bonglv/bbytesolutions.com:1.0
    ports:
    # Exposes port 80 for incomming web requests
    - 80:80
    - 443:443
    labels:
      - traefik.enable=true
      - traefik.http.routers.bbytesolutions.rule=Host('home.bbytegroup.com')
      - traefik.http.routers.bbytesolutions.entrypoints=web
      - traefik.http.routers.bbytesolutions.service=bbytesolutions
      - traefik.http.routers.bbytesolutions.loadbalancer.server.port=300001
    networks:
      - traefik-public
    deploy: 
      mode: replicated
      replicas: 2
networks:
  traefik-public:
    external: true