version: '3.8'

services:
  home:
    image: bonglv/home:latest
    environment:
      - HOSTNAME=home.bbytegroup.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.home-http.rule=Host(`home.bbytegroup.com`)
        - traefik.http.routers.home-http.entrypoints=http
        - traefik.http.routers.home-http.middlewares=https-redirect
        - traefik.http.routers.home-https.rule=Host(`home.bbytegroup.com`)
        - traefik.http.routers.home-https.entrypoints=https
        - traefik.http.routers.home-https.tls=true
        - traefik.http.routers.home-https.tls.certresolver=le
        - traefik.http.services.home.loadbalancer.server.port=9999
        - traefik.http.services.ombi.loadbalancer.server.scheme=https
networks:
  traefik-public:
    external: true